trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: component
  displayName: 'Select Component'
  type: string
  default: 'ATG'
  values:
  - ATG
  - GROUND
  - HMI

- name: libraryVersion
  type: string
  default: '1.0.0'

jobs:
- job: GenerateLibrary
  displayName: 'Generate Component Library'
  steps:
  - checkout: self
  
  - script: |
      echo "Generating library for component ${{ parameters.component }} with version ${{ parameters.libraryVersion }}"
      git clone https://github.com/racemusconsulting/poc-idl-cdl-files.git
    displayName: 'Checkout IDL and CDL Files'
  
  - script: |
      mvn clean install -Dcomponent=${{ parameters.component }} -Dversion=${{ parameters.libraryVersion }} -DidlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/IDLS -DcdlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/CDLS
      echo "Library generation command executed"
    displayName: 'Generate Library'
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'deploy -Dcomponent=${{ parameters.component }} -Dversion=${{ parameters.libraryVersion }} -DidlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/IDLS -DcdlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/CDLS'
      options: '-DskipTests -DaltDeploymentRepository=snapshotRepo::default::https://pkgs.dev.azure.com/racemusconsulting/_packaging/${{ parameters.component }}-middleware-connector/maven/v1'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: true
    displayName: 'Publish Artifact to Azure Artifacts'
