trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: component
  displayName: 'Select Component'
  type: string
  default: 'ATG'
  values:
  - ATG
  - GROUND
  - HMI

- name: libraryVersion
  type: string
  default: '1.0.0'

jobs:
- job: GenerateLibrary
  displayName: 'Generate Component Library'
  steps:
  - checkout: self

  - script: |
      wget https://www.jacorb.org/releases/3.9/jacorb-3.9-binary.zip
      unzip jacorb-3.9-binary.zip
      echo "JACORB successfully installed"
      # Set JACORB_HOME environment variable
      ls -al $JACORB_HOME/bin
      echo "##vso[task.setvariable variable=JACORB_HOME]$(pwd)/jacorb-3.9"
    displayName: 'Install JACORB and Set JACORB_HOME'

  - script: |
      echo "Generating library for component ${{ parameters.component }} with version ${{ parameters.libraryVersion }}"
      git clone https://github.com/racemusconsulting/poc-idl-cdl-files.git
    displayName: 'Checkout IDL and CDL Files'

  - task: Maven@3
    displayName: Build
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'clean -Dcomponent=${{ parameters.component }}  -Dproject.artifactId=${{ parameters.component }}-middleware-connector -Dproject.version=${{ parameters.libraryVersion }} -DidlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/IDLS -DcdlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/CDLS'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      mavenAuthenticateFeed: true
      publishJUnitResults: false
      goals: 'jar:jar deploy:deploy'
    displayName: 'Publish Artifact to Azure Artifacts'
  
