trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  cdlFolderPath: 'path/to/CDLs' # Update this path as necessary

steps:
  - checkout: self
    submodules: true

  - script: echo Starting CI pipeline...
    displayName: 'Echo start message'

  # Assuming ZIP file is in your repo, if not you need to upload it manually to a cloud storage and download it here
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'idlZip' # Name of the artifact
      itemPattern: '**/*.zip' # Pattern to match zip files
      targetPath: '$(Build.SourcesDirectory)/idlFiles'

  # Extract IDL Files from ZIP
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Build.SourcesDirectory)/idlFiles/*.zip'
      destinationFolder: '$(Build.SourcesDirectory)/extractedIDLs'
      cleanDestinationFolder: true
    displayName: 'Extract IDL Files from ZIP'

  # Compilation and Unit Tests
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean compile'
      options: ''
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    displayName: 'Maven Compile and Unit Tests'

  # BDD Tests
  - script: mvn verify -Pbdd
    displayName: 'Run BDD Tests'

  # Library Generation
  - script: |
      mvn clean install -DidlFolderPath=$(Build.SourcesDirectory)/extractedIDLs -DcdlFolderPath=$(cdlFolderPath)
    displayName: 'Generate Library from IDLs and CDLs'


  # Publish Artifact to Azure Artifacts
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'deploy'
      options: '-DskipTests -DaltDeploymentRepository=snapshotRepo::default::https://pkgs.dev.azure.com/yourOrganization/_packaging/yourFeed/maven/v1'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: true
    displayName: 'Publish Artifact to Azure Artifacts'
