trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: component
  displayName: 'Select Component'
  type: string
  default: 'AIR'
  values:
  - AIR
  - GROUND
  - HMI

- name: libraryVersion
  type: string
  default: '1.0.0'

jobs:
- job: GenerateLibrary
  displayName: 'Generate Component Library'
  steps:
  - checkout: self
  
  - script: |
      echo "Generating library for component ${{ parameters.component }} with version ${{ parameters.libraryVersion }}"
      # Add commands to checkout IDL/CDL files based on selected component
      # e.g., git clone <repo-url>/<${{ parameters.component }}>.git
    displayName: 'Checkout IDL and CDL Files'
  
  - script: |
      # Add your library generation commands here
      # Example: mvn clean install -Dcomponent=${{ parameters.component }} -Dversion=${{ parameters.libraryVersion }}
      echo "Library generation command would go here"
    displayName: 'Generate Library'
  
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/path/to/generated/lib'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/${{ parameters.component }}'
    displayName: 'Copy Generated Library'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/${{ parameters.component }}'
      ArtifactName: 'GeneratedLibrary-${{ parameters.component }}'
      publishLocation: 'container'
    displayName: 'Publish Generated Library as Artifact'
