trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: component
  displayName: 'Select Component'
  type: string
  default: 'ATG'
  values:
  - ATG
  - GROUND
  - HMI

- name: libraryVersion
  type: string
  default: '1.0.0-SNAPSHOT'

jobs:
- job: GenerateLibrary
  displayName: 'Generate Component Library'
  steps:
  - checkout: self

  - script: |
      wget https://www.jacorb.org/releases/3.9/jacorb-3.9-binary.zip
      unzip jacorb-3.9-binary.zip
      echo "JACORB successfully installed"
      # Set JACORB_HOME environment variable
      ls -al $JACORB_HOME/bin
      echo "##vso[task.setvariable variable=JACORB_HOME]$(pwd)/jacorb-3.9"
    displayName: 'Install JACORB and Set JACORB_HOME'

  - script: |
      echo "Generating library for component ${{ parameters.component }} with version ${{ parameters.libraryVersion }}"
      git clone https://github.com/racemusconsulting/poc-idl-cdl-files.git
    displayName: 'Checkout IDL and CDL Files'


  - script: |
      sed -i 's|<artifactId>xxxx</artifactId>|<artifactId>${{ parameters.component }}-middleware-connector</artifactId>|' pom.xml
      sed -i 's|<version>xxxx</version>|<version>${{ parameters.libraryVersion }}</version>|' pom.xml
    displayName: 'Modify pom.xml with dynamic artifactId and version'

  - task: Maven@3
    displayName: Build
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'clean verify -Dcomponent=${{ parameters.component }} -DidlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/IDLS -DcdlFolderPath=poc-idl-cdl-files/${{ parameters.component }}/CDLS'

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'atg'
      mavenServiceConnections: 'mavenfeed'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      mavenAuthenticateFeed: true
      publishJUnitResults: false
      goals: 'jar:jar deploy:deploy -Dcomponent=${{ parameters.component }} '
    displayName: 'Publish Artifact to Azure Artifacts'
  
